[project]
name = "evo-data-converters-obj"
description = "Python data converters for Wavefront Technologies OBJ/MTL file to Evo geoscience objects"
version = "0.0.1"
requires-python = ">=3.10"
license-files = ["LICENSE.md"]
dynamic = ["readme"]
authors = [
    { name = "Seequent", email = "support@seequent.com" }
]
dependencies = [
    "evo-data-converters-common",
    "trimesh>=4.9.0",
]

[project.optional-dependencies]
optional_parsers = [
    "open3d-cpu>=0.19.0",
    "pyassimp>=5.2.5",
    "tinyobjloader",
]

[dependency-groups]
dev = [
    "memray>=1.19.1",
    "pytest",
]

[tool.ruff]
src = ["src", "tests"]
line-length = 120
[build-system]
requires = ["hatchling", "hatch-fancy-pypi-readme"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
include = ["src"]

[tool.hatch.build.targets.wheel]
packages = ["src/evo"]

[tool.hatch.metadata.hooks.fancy-pypi-readme]
content-type = "text/markdown"

[[tool.hatch.metadata.hooks.fancy-pypi-readme.fragments]]
path = "README.md"

[[tool.hatch.metadata.hooks.fancy-pypi-readme.substitutions]]
# Literal TOML strings (single quotes) need no escaping of backslashes.
# Converts relative links to absolute links in PyPI
pattern = '\[(.+?)\]\(((?!https?://)\S+?)\)'
replacement = '[\1](https://github.com/SeequentEvo/evo-data-converters/tree/main/packages/obj/\g<2>)'

[tool.uv.sources]
tinyobjloader = { git = "https://github.com/tinyobjloader/tinyobjloader.git" }
